//Suit / Shirt / Pants/ Shoes / Watches
module.exports =  [
    [{
        id: 1,
        name: 'Blue Suit',
        color: 'Blue',
        article: 'Suit',
        type: 'Buisness',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'true',
    },
    {   id: 2,
        name: 'Black Suit',
        color: 'Black',
        article: 'Suit',
        type: 'Buisness',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 3,
        name: 'Grey Suit',
        color: 'Grey',
        article: "Suit",
        type: 'Formal',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 4,
        name: 'Blue Suit 2',
        color: 'Blue',
        article: 'Suit',
        type: 'Buisness',
        favorite: 'false',
        dateworn: "1548532490265",
        laundry: 'false' },
    {   id: 5,
        name: 'Casual Suit',
        color: 'Brown',
        article: 'Suit',
        type:'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'}],
     [{
        id: 1,
        name: 'White Dress Shirt',
        color: 'White',
        article: 'Shirt',
        type: 'Buisness',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'true',
    },
    {   id: 2,
        name: 'Blue tee',
        color: 'Blue',
        article: 'T-shirt',
        type: 'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 3,
        name: 'Panda shirt',
        color: 'Grey',
        article: "Shirt",
        type: 'Casual',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 4,
        name: 'Button up',
        color: 'Blue',
        article: 'Shirt',
        type: 'Casual',
        favorite: 'false',
        dateworn: "1548532490265",
        laundry: 'false' },
    {   id: 5,
        name: 'Black Tshirt',
        color: 'Black',
        article: 'Tshirt',
        type:'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'}],
     [{
        id: 1,
        name: 'Blue Pants',
        color: 'Blue',
        article: 'Pants',
        type: 'Buisness',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'true',
    },
    {   id: 2,
        name: 'Jeans',
        color: 'Black',
        article: 'Pants',
        type: 'Casual',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 3,
        name: 'Dress Pants',
        color: 'Black',
        article: "pants",
        type: 'Formal',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 4,
        name: 'Jeans',
        color: 'Blue',
        article: 'Pants',
        type: 'Casual',
        favorite: 'false',
        dateworn: "1548532490265",
        laundry: 'false' },
    {   id: 5,
        name: 'Shorts',
        color: 'Brown',
        article: 'Pants',
        type:'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'}],
    [{
        id: 1,
        name: 'Blue Suit',
        color: 'Blue',
        article: 'Suit',
        type: 'Buisness',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'true',
    },
    {   id: 2,
        name: 'dress shoes',
        color: 'Black',
        article: 'Shoes',
        type: 'Buisness',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 3,
        name: 'Converse',
        color: 'Red',
        article: "Shoes",
        type: 'Casual',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 4,
        name: 'Clean Boots',
        color: 'Blue',
        article: 'Shoes',
        type: 'Casual',
        favorite: 'false',
        dateworn: "1548532490265",
        laundry: 'false' },
    {   id: 5,
        name: 'Sandals',
        color: 'Brown',
        article: 'Shoes',
        type:'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'}],
    [{
        id: 1,
        name: 'Gift from Amy',
        color: 'Silver',
        article: 'Watch',
        type: 'Buisness',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'true',
    },
    {   id: 2,
        name: 'Geoforce',
        color: 'Black',
        article: 'Watch',
        type: 'Casual',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 3,
        name: 'Apple Watch',
        color: 'White',
        article: "Watch",
        type: 'Formal',
        favorite: 'true',
        dateworn: '1548532490265',
        laundry: 'false'},
    {   id: 4,
        name: 'Skeleton',
        color: 'Black',
        article: 'Watch',
        type: 'Formal',
        favorite: 'false',
        dateworn: "1548532490265",
        laundry: 'false' },
    {   id: 5,
        name: 'Workout Watch',
        color: 'Black',
        article: 'Watch',
        type:'Casual',
        favorite: 'false',
        dateworn: '1548532490265',
        laundry: 'false'}],
]